version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/elasticsearch-rails/
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  mysql_data:
